- name: remove packages
  hosts: localhost
  become: yes

  tasks:
    - name: remove
      dnf:
        state: absent
        name:
          - PackageKit
          - cheese
          - gamemode
          - tracker

  tasks:
- name: configure repos and install packages
  hosts: localhost
  become: yes

  tasks:
    - name: add rpmfusion repos 
      dnf:
        name: "{{ item }}"
        state: latest
        disable_gpg_check: yes # not recommended
      loop:
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: patch system
      dnf:
        update_cache: yes
        name: "*"
        state: latest

    - name: install packages
      dnf:
        update_cache: yes
        name:
          - arp-scan
          - baobab
          - bash-completion
          - borgbackup
          - blender
          - ffmpeg
          - fping
          - git
          - golang
          - htop
          - keepassxc
          - ImageMagick
          - java-11-openjdk
          - lm_sensors
          - mplayer
          - mpv
          - neofetch
          - nethogs
          - newsboat
          - nmap
          - obs-studio
          - pcmanfm
          - python3-devel
          - python3-streamlink
          - redshift-gtk
          - rkhunter
          - rsync
          - sshfs
          - stow
          - syncthing
          - texlive
          - texlive-preprint
          - texstudio
          - tlp
          - tmux 
          - units
          - unrar
          - vim
          - virt-manager
          - vlc
          - wireshark
          - youtube-dl
        state: latest

    - name: pip3 pkgs
      pip:
        name:
          - thefuck
          - mps-youtube
          - dbus-python
          - pygobject

- name: remove default fluff
  hosts: localhost
  become: yes

  tasks:
    - name: get local user name
      command: whoami
      changed_when: false
      become: false
      register: whoami

    - name: remove default directories
      file:
        state: absent
        path: "/home/{{ whoami.stdout }}/{{ item }}"
      loop:
        -  "Public"
        - "Templates"

- name: use NetworkManager for DNS
  hosts: localhost
  become: yes

  tasks:
    - name: disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
        maked: yes

    - name: remove /etc/resolv.conf symlink
      file:
        path: /etc/resolv.conf
        state: absent

    - name: replace line in NetworkManager.conf
      replace:
        regexp: '#dns=default'
        replace: 'dns=default'

    - name: restart network manager
      systemd:
        name: NetworkManager
        state: restarted

- name: GNOME keyboard shortcuts
  hosts: localhost
  become: yes

  tasks:
    - name: terminal shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'Open Terminal'"
    - name: terminal shortcut command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'gnome-terminal'"
    - name: terminal shortcut binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'Menu'"   

    - name: screenshot shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
        value: "'Take Interactive Screenshot'"
    - name: screenshot shortcut command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
        value: "'gnome-screenshot -i'"
    - name: screenshot shortcut binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
        value: "'Print'"   

- name: GNOME keyboard shortcuts
  hosts: localhost
  roles: 
    - role: gnome_extensions
      vars:
        gnome_extension_ids:
          - 615 # AppIndicator and KStatusNotifierItem Support
          - 751 # Audio Output Switcher
          - 517 # Caffeine
          - 1166 # Extension Update Notifier
          - 755 # Hibernate Status Button
          - 1128 # Hide Activities Button
          - 1379 # Mpris Indicator Button
          - 355 # Status Area Horizontal Spacing
          - 1460 # Vitals

